### ISSUE TITLE
视频功能导入文件就崩溃

### ISSUE THREAD

**Issue by Daish98** [haochenheheda/segment-anything-annotator#24]
￼Traceback (most recent call last):
  File "annotator_video.py", line 309, in <lambda>
    lambda: self.clickSaveChoose(),
  File "annotator_video.py", line 746, in clickSaveChoose
    self.loadImg()
  File "annotator_video.py", line 697, in loadImg
    self.raw_h, self.raw_w = cv2.imread(self.current_img).shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
已放弃 (核心已转储)

**Comment by JoaoCH** [comment]
Hi,

I had the same error and in my case it was because the file extension was in uppercase.

I changed the code to the following:
 
`self.img_list = glob.glob(directory + '/*.jpg') + glob.glob(directory + '/*.png') + glob.glob(directory + '/*.JPG') #I change this line`
