### ISSUE TITLE
sudden exit with the typeerror with drawText on m1 mac

### ISSUE THREAD

**Issue by peterhuang621** [haochenheheda/segment-anything-annotator#3]
Hello,
I have tried several times by your instruction in demo image and each time when I successfully load the SAM, any further step: 'Point Prompt', 'Box Prompt' or 'Manual Polygons' will exit the program once I click on the pic. The error message shows as below:
 
`python annnotator.py --app_resolution 1000,1600 --model_type vit_b --keep_input_size True --max_size 720
2023-04-18 11:57:16.074 python[36573:3837983] +[CATransaction synchronize] called within transaction
2023-04-18 11:57:17.887 python[36573:3837983] +[CATransaction synchronize] called within transaction
2023-04-18 11:57:23.813 python[36573:3837983] +[CATransaction synchronize] called within transaction
2023-04-18 11:57:38.869 python[36573:3837983] +[CATransaction synchronize] called within transaction
2023-04-18 11:58:02.440 python[36573:3837983] +[CATransaction synchronize] called within transaction
vit_b model already exists as 'vit_b.pth'. Skipping download.
Traceback (most recent call last):
  File "/Users/peterhuang/Documents/test_code/Python/segment-anything-annotator-master/canvas.py", line 921, in paintEvent
    self.current.paint(p)
  File "/Users/peterhuang/Documents/test_code/Python/segment-anything-annotator-master/shape.py", line 213, in paint
    painter.drawText(cx, cy, self.label)
TypeError: arguments did not match any overloaded call:
  drawText(self, p: Union[QPointF, QPoint], s: str): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRectF, flags: int, text: str): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRect, flags: int, text: str): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRectF, text: str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'float'
  drawText(self, p: QPoint, s: str): argument 1 has unexpected type 'float'
  drawText(self, x: int, y: int, width: int, height: int, flags: int, text: str): argument 1 has unexpected type 'float'
  drawText(self, x: int, y: int, s: str): argument 1 has unexpected type 'float'
zsh: abort      python annnotator.py --app_resolution 1000,1600 --model_type vit_b  True  720
`

My device is M1 chic Macbook air and python version is 3.10.10. Would you have any idea to solve this problem? Thank you so much.

**Comment by haochenheheda** [comment]
should be fixed, please try again

**Comment by haochenheheda** [comment]
Please update shape.py
https://github.com/haochenheheda/segment-anything-annotator/blob/e3dcb850ea91bd0ed701216113c0f2cf20f0dbc7/shape.py#L209-L213

**Comment by peterhuang621** [comment]
Perfect! It works now. Thanks for your quick reply!!!
在知乎上看到大佬的帖子了，膜拜膜拜，非常感谢

**Comment by GuanchengWan** [comment]
@peterhuang621 m1 mac怎么安装pyqt5呀，我brew安装完这个项目之后报错cannot import name 'qtwidgets' from 'pyqt5'，大佬能指个路吗，谢谢

**Comment by peterhuang621** [comment]
pyqt5原生好像不支持m1，所以直接装不了（pyqt6好像支持了）
一定用conda install pyqt，好像是anaconda上的模块包都是编译好的跟pip包不太一样，具体原理我也不太清楚。。。
