### ISSUE TITLE
Errors often occur during annotation

### ISSUE THREAD

**Issue by CalvinSMU** [haochenheheda/segment-anything-annotator#5]
Traceback (most recent call last):
  File "F:\Project\Segment_Anything\segment-anything-annotator\canvas.py", line 514, in mousePressEvent
    self.app.clickManualSegBox()
  File "F:\Project\Segment_Anything\segment-anything-annotator\annnotator.py", line 862, in clickManualSegBox
    group_id=self.getMaxId() + 1,
  File "F:\Project\Segment_Anything\segment-anything-annotator\annnotator.py", line 704, in getMaxId
    max_id = max(max_id, label.shape().group_id)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by haochenheheda** [comment]
Fixed.
